#TASK9.1: Sum even and odd numbers with docstring comparison
def sum_even_odd(numbers):
    # DOCSTRING WRITTEN MANUALLY
    """
    Calculate the sum of even and odd numbers in a list.

    Args:
        numbers (list[int]): A list of integers entered by the user.

    Returns:
        tuple: A tuple containing:
            - int: Sum of even numbers.
            - int: Sum of odd numbers.

    Raises:
        TypeError: If input contains non-integer values.
    """
    if any(not isinstance(n, int) for n in numbers):
        raise TypeError("All values must be integers.")

    even_sum = sum(n for n in numbers if n % 2 == 0)
    odd_sum = sum(n for n in numbers if n % 2 != 0)

    return even_sum, odd_sum


# ✅ USER INPUT PART
user_input = input("Enter numbers separated by spaces: ")
num_list = list(map(int, user_input.split()))

even_total, odd_total = sum_even_odd(num_list)

print("Sum of even numbers:", even_total)
print("Sum of odd numbers:", odd_total)

#DOCSTRING GENERATED BY COPILOT:
#def sum_even_odd(numbers):
"""
    Returns the sum of even and odd numbers in a list.

    Parameters:
        numbers (list): List of integers.

    Returns:
        tuple: (sum_of_even, sum_of_odd)
    """
