#TASK 9.3
#  DOCSTRING WRITTEN MANUALLY 
"""
Calculator Module
-----------------
This module provides basic arithmetic operations such as addition,
subtraction, multiplication, and division. It allows reuse of simple math
functions inside larger programs.
"""

def add(a, b):
    """
    Add two numbers.

    Parameters
    ----------
    a : float or int
        First number.
    b : float or int
        Second number.

    Returns
    -------
    float or int
        The sum of the two numbers.

    Examples
    --------
    >>> add(3, 5)
    8
    """
    return a + b


def subtract(a, b):
    """
    Subtract one number from another.

    Parameters
    ----------
    a : float or int
        Number from which another value will be subtracted.
    b : float or int
        Number to subtract.

    Returns
    -------
    float or int
        The result of a - b.

    Examples
    --------
    >>> subtract(10, 4)
    6
    """
    return a - b


def multiply(a, b):
    """
    Multiply two numbers.

    Parameters
    ----------
    a : float or int
        First number.
    b : float or int
        Second number.

    Returns
    -------
    float or int
        Product of a and b.

    Examples
    --------
    >>> multiply(4, 2)
    8
    """
    return a * b


def divide(a, b):
    """
    Divide one number by another.

    Parameters
    ----------
    a : float or int
        Numerator.
    b : float or int
        Denominator.

    Returns
    -------
    float or int
        Result of a / b.

    Raises
    ------
    ZeroDivisionError
        If ``b`` is zero.

    Examples
    --------
    >>> divide(10, 2)
    5.0
    """
    if b == 0:
        raise ZeroDivisionError("Cannot divide by zero.")
    return a / b

print("The result of addition is:", add(3, 5))
print("The result of subtraction is:", subtract(10, 4))
print("The result of multiplication is:", multiply(2, 6))
print("The result of division is:", divide(10, 2))

# DOCSTRING GENERATED BY COPILOT:
"""
A simple calculator module that provides basic arithmetic functions:
add, subtract, multiply, and divide.
"""
def add(a, b):
    """Returns the sum of two numbers."""
    return a + b

def subtract(a, b):
    """Returns the difference between two numbers."""
    return a - b

def multiply(a, b):
    """Returns the product of two numbers."""
    return a * b

def divide(a, b):
    """Returns the result of dividing a by b."""
    return a / b
