#TASK 9.2 
# MANUALLY DONE DOCSTRING FOR CLASS sru_student
class sru_student:
    # Constructor to initialize student details
    def __init__(self, name, roll_no, hostel_status):
        self.name = name               # Store student's name
        self.roll_no = roll_no         # Store student's roll number
        self.hostel_status = hostel_status  # Store hostel status (Yes/No)
        self.fee = 0                   # Initialize fee to 0

    # Method to update student fee
    def fee_update(self, amount):
        self.fee = amount              # Assign the given amount to fee

    # Method to display details of the student
    def display_details(self):
        print("---- Student Details ----")     # Print heading
        print("Name:", self.name)              # Print student's name
        print("Roll No:", self.roll_no)        # Print roll number
        print("Hostel Status:", self.hostel_status)  # Print hostel status
        print("Total Fee:", self.fee)          # Print updated fee


# Taking user input for student attributes
name = input("Enter student name: ")                     # Ask for name
roll_no = input("Enter roll number: ")                   # Ask for roll no
hostel_status = input("Is the student in hostel? (Yes/No): ")  # Ask hostel status

# Creating object of sru_student class
student1 = sru_student(name, roll_no, hostel_status)     # Create object using user data

# Taking fee input and updating
fee_amount = int(input("Enter fee amount: "))            # Ask for fee
student1.fee_update(fee_amount)                          # Update fee

# Display all the details
student1.display_details()                               # Show all info

#DOCSTRING GENERATED BY COPILOT:
class sru_student:
    # Initialize class attributes
    def __init__(self, name, roll_no, hostel_status):
        self.name = name
        self.roll_no = roll_no
        self.hostel_status = hostel_status
        self.fee = 0
    # Update fee value
    def fee_update(self, amount):
        self.fee = amount
    # Print student information
    def display_details(self):
        print("---- Student Details ----")
        print("Name:", self.name)
        print("Roll No:", self.roll_no)
        print("Hostel Status:", self.hostel_status)
        print("Total Fee:", self.fee)
# Get input from user
name = input("Enter student name: ")
roll_no = input("Enter roll number: ")
hostel_status = input("Is the student in hostel? (Yes/No): ")
# Create student object
student1 = sru_student(name, roll_no, hostel_status)
# Get fee amount
fee_amount = int(input("Enter fee amount: "))
# Update fee
student1.fee_update(fee_amount)
# Display data
student1.display_details()
